---
site_name: Numerically stable fixed-point smoothing in JAX
theme:
  name: material
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_signature: true
            show_signature_annotations: true
            show_if_no_docstring: false
nav:
  - 'API: fpx Package': index.md
